// Wreaths data
const wreaths = [
  {
    id: 1,
    name: "Венок-сердце с белыми розами",
    price: 4500,
    image: "photovenok1.jpg",
    category: "Элитные",
    rating: 5,
    description: "Изысканный венок в форме сердца из белых роз с зеленой атласной лентой",
  },
  {
    id: 2,
    name: "Венок с серебряной лентой",
    price: 3800,
    image: "venok10.jpg",
    category: "Классические",
    rating: 5,
    description: "Торжественный венок с красными розами, белыми цветами и серебряной лентой",
  },
  {
    id: 3,
    name: "Венок с ирисами и розами",
    price: 4200,
    image: "venok11.jpg",
    category: "Элитные",
    rating: 5,
    description: "Элегантный венок с белыми розами и фиолетовыми ирисами в серебряном обрамлении",
  },
  {
    id: 4,
    name: "Венок с синими гвоздиками",
    price: 2800,
    image:"venok12.jpg",
    category: "Традиционные",
    rating: 4,
    description: "Классический венок с синими гвоздиками и белой лентой",
  },
  {
    id: 5,
    name: "Венок с красными розами и хризантемами",
    price: 3600,
    image: "venok13.jpg",
    category: "Классические",
    rating: 5,
    description: "Яркий венок с красными розами, белыми хризантемами и красной лентой",
  },
  {
    id: 6,
    name: "Венок с желтыми цветами",
    price: 3400,
    image: "venok14.jpg",
    category: "Сезонные",
    rating: 4,
    description: "Солнечный венок с желтыми и красными цветами в красном обрамлении",
  },
  {
    id: 7,
    name: "Венок с фиолетовыми гвоздиками",
    price: 4000,
    image: "venok15.jpg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный венок с фиолетовыми гвоздиками и белыми лилиями",
  },
  {
    id: 8,
    name: "Венок-сердце с черной лентой",
    price: 5200,
    image: "venok15.jpg",
    category: "Элитные",
    rating: 5,
    description: "Траурный венок в форме сердца с красными гвоздиками и черной лентой",
  },
  {
    id: 9,
    name: "Венок-сердце с красными гвоздиками",
    price: 4800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok8.jpg-M9JpMUMIsv7JfeooIhQZjCcJfSmfrn.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Классический венок-сердце с белыми розами и красными гвоздиками",
  },
  {
    id: 10,
    name: "Венок-сердце с красными розами",
    price: 5500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok11.jpg-cdIrZbWawgIMpSH4UfnVoBYmqlLy1O.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный венок-сердце с красными розами и белыми цветами в красном обрамлении",
  },
  {
    id: 11,
    name: "Классический венок с белыми лилиями",
    price: 3900,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok13.jpg-b5BWJqa2g5qq9sr0OuIQ1JOn5iIR2G.jpeg",
    category: "Классические",
    rating: 5,
    description: "Элегантный венок с белыми лилиями и зеленой листвой",
  },
  {
    id: 12,
    name: "Венок-сердце с белыми гвоздиками",
    price: 4300,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok14.jpg-Pg2TvU0N57EPfTQp7OigR840oYZWAP.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Нежный венок-сердце с белыми гвоздиками в красном обрамлении",
  },
  {
    id: 13,
    name: "Венок-сердце с лилиями",
    price: 4700,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok12.jpg-cD7jamieeJoCKTPKrqrKrDeA513TsE.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Изысканный венок-сердце с белыми гвоздиками и лилиями в красном обрамлении",
  },
  {
    id: 14,
    name: "Большой элитный венок с белыми розами",
    price: 7500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok15.jpg-OPlJz0IpVnoddbyuC4GbgHL2Iywc4c.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный большой венок с белыми розами и лилиями в белом обрамлении с золотой каймой",
  },
  {
    id: 15,
    name: "Венок-сердце с красными гвоздиками",
    price: 4600,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok18.jpg-VJQscMMILsZm24KwvCYZf0BMVKp9Dc.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Классический венок-сердце с красными гвоздиками и белыми розами в черном обрамлении",
  },
  {
    id: 16,
    name: "Венок-сердце с хризантемами",
    price: 4400,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok19.jpg-wevHUbiUE0DXL4cbvwwZhabwsNutgE.jpeg",
    category: "Классические",
    rating: 5,
    description: "Красивый венок-сердце с красными розами и белыми хризантемами",
  },
  {
    id: 17,
    name: "Большой овальный венок с белыми розами",
    price: 6800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok17.jpg-S9ISluwWTmVy0OcWvv0JuwDYhWgggc.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Элитный большой овальный венок с белыми розами в серебряном обрамлении",
  },
  {
    id: 18,
    name: "Овальный венок с красными розами",
    price: 5900,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok20.jpg-QSU6GXejyMAsfxrxyNVDDmcmYi4vsG.jpeg",
    category: "Классические",
    rating: 5,
    description: "Торжественный овальный венок с красными розами и белыми лилиями в серебряном обрамлении",
  },
  {
    id: 19,
    name: "Большой венок с желтыми розами",
    price: 6200,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok16.jpg-j0Hdzhfx2sAtKIP1ESLF5gRvLolIER.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Яркий большой овальный венок с желтыми и белыми розами в черном обрамлении",
  },
  {
    id: 20,
    name: "Овальный венок 'Память'",
    price: 4900,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok22.jpg-tJQKCwBtiQndSbqOtllyIYFutkg4Gz.jpeg",
    category: "Классические",
    rating: 5,
    description: "Элегантный овальный венок с белыми хризантемами и красными цветами в бордовом обрамлении",
  },
  {
    id: 21,
    name: "Овальный венок 'Солнечный'",
    price: 5300,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok24.jpg-6FBWeEHqcD80nPBHxHi7xyrq9tCyQz.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Яркий овальный венок с желтыми и красными гвоздиками в красном атласном обрамлении",
  },
  {
    id: 22,
    name: "Овальный венок 'Торжественный'",
    price: 6100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok25.jpg-X575OVACdtCxFOVE3Ru1ZGK09c9SzY.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный овальный венок с красными гвоздиками и белыми лилиями в золотом обрамлении",
  },
  {
    id: 23,
    name: "Овальный венок 'Классика'",
    price: 5700,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok23.jpg-ZTStU4hVh4uH6J1ls5GiCnbF9Gutwl.jpeg",
    category: "Классические",
    rating: 5,
    description: "Изысканный овальный венок с красными розами и белыми гвоздиками в золотом обрамлении",
  },
  {
    id: 24,
    name: "Овальный венок 'Роскошь'",
    price: 7200,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok21.jpg-19BoHoWTGYFQjsxt47PgTkoDORj9xL.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Премиальный овальный венок с множеством красных роз и белыми цветами в золотом обрамлении",
  },
  {
    id: 25,
    name: "Овальный венок 'Золотой'",
    price: 6500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok29.jpg-2tcpM6eYIMn4UXYq3kEZnbKafLv9dA.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный овальный венок с желтыми розами и белыми каллами в золотом обрамлении",
  },
  {
    id: 26,
    name: "Овальный венок 'Весенний'",
    price: 5800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok28.jpg-d6xfrEAF5vdRJR9XywbXlqqBx67gDn.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Свежий овальный венок с белыми и желтыми цветами в зеленом атласном обрамлении",
  },
  {
    id: 27,
    name: "Овальный венок 'Контраст'",
    price: 5600,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok27.jpg-JAQml3g0vwSbFI1dvynz3Z5AoSzY2d.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Стильный овальный венок с розовыми и желтыми розами в серебряном обрамлении",
  },
  {
    id: 28,
    name: "Овальный венок 'Нежность'",
    price: 4800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok26.jpg-LhMeJhlbvuyNQiOj4eHYxExUa1n2Wl.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Нежный овальный венок с белыми розами и мелкими белыми цветами в зеленом обрамлении",
  },
  {
    id: 29,
    name: "Овальный венок 'Солнце'",
    price: 5400,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok31.jpg-Vw8mmpPhkST3GbvfU7mArxMK9SgCy8.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Яркий овальный венок с желтыми розами в желтом атласном обрамлении",
  },
  {
    id: 30,
    name: "Овальный венок 'Элегантность'",
    price: 5400,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok34.jpg-viI0TjxhwUd6cBU5BQ7pq4tVUU0rdG.jpeg",
    category: "Классические",
    rating: 5,
    description: "Изысканный овальный венок с белыми хризантемами и красными розами в зеленом обрамлении",
  },
  {
    id: 31,
    name: "Овальный венок 'Нежный персик'",
    price: 5800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok36.jpg-zoCEhGJqQRG8V9flXXs400PaH6pEtc.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Роскошный овальный венок с фиолетовыми гвоздиками, персиковыми розами и белыми цветами",
  },
  {
    id: 32,
    name: "Овальный венок 'Королевский фиолетовый'",
    price: 6800,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok33.jpg-6LcUrmQhPg78tGoVwU5Ik6dsNfxdJ4.jpeg",
    category: "Элитные",
    rating: 5,
    description: "Премиальный овальный венок с фиолетовыми гвоздиками в декоративном обрамлении с белой лентой",
  },
  {
    id: 33,
    name: "Овальный венок 'Яркая фуксия'",
    price: 5200,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok35.jpg-eUinEfiSeSL5wImIn6V1wVS06EAm15.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Яркий овальный венок с розовыми гвоздиками внизу и смешанными розовыми и белыми цветами вверху",
  },
  {
    id: 34,
    name: "Овальный венок 'Фиолетовая роскошь'",
    price: 6200,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok32.jpg-mraorEuOIojLGoTjUnfF7NV9B4Eptv.jpeg",
    category: "Элитные",
    rating: 5,
    description:
      "Элегантный овальный венок с фиолетовыми розами в центре и розовыми гвоздиками по краю с серебряной лентой",
  },
  {
    id: 35,
    name: "Венок-сердце 'Синее небо'",
    price: 4900,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok39.jpg-mqSsB1Rq33fYVFg1NwVr5K6ARDvYJB.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Нежный венок-сердце с синими гвоздиками и белыми розами в бело-золотом обрамлении",
  },
  {
    id: 36,
    name: "Овальный венок 'Солнечные лилии'",
    price: 5600,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok38.jpg-dceVglFdBwSY8OUzYa1xR6rApkXxCf.jpeg",
    category: "Сезонные",
    rating: 5,
    description: "Яркий овальный венок с оранжевыми лилиями в центре и красно-желтыми гвоздиками по краю",
  },
  {
    id: 37,
    name: "Овальный венок 'Фиолетовая мечта'",
    price: 5900,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok530.jpg-mUxmrvAOiR7mvM4dIFHqkCA1Vzhide.jpeg",
    category: "Элитные",
    rating: 5,
    description:
      "Роскошный овальный венок с фиолетовыми розами в центре и белыми гвоздиками по краю в серебряном обрамлении",
  },
  {
    id: 38,
    name: "Венок-сердце 'Красная любовь'",
    price: 5100,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok65.jpg-dX2NpcHnX0zT840RkuozjTdny5nELI.jpeg",
    category: "Традиционные",
    rating: 5,
    description: "Классический венок-сердце с красными розами по краю и зеленой листвой в центре с белым обрамлением",
  },
  {
    id: 39,
    name: "Овальный венок 'Красно-белая классика'",
    price: 5500,
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/venok37.jpg-OI2tW4qVGaQjsmKI3r8I9oq4fnXidI.jpeg",
    category: "Классические",
    rating: 5,
    description:
      "Традиционный овальный венок с красными розами, белыми ромашками в центре и красно-белыми гвоздиками по краю",
  },
  {
    id: 40,
    name: "Овальный венок 'Белоснежная элегантность'",
    price: 6300,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "Элитные",
    rating: 5,
    description:
      "Роскошный овальный венок с белыми розами и черными траурными лентами в белом обрамлении с золотой каймой",
  },
  {
    id: 41,
    name: "Круглый венок 'Солнечное сияние'",
    price: 5700,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "Сезонные",
    rating: 5,
    description:
      "Яркий круглый венок с желтыми розами в центре и черным декоративным обрамлением с золотыми элементами",
  },
  {
    id: 42,
    name: "Овальный венок 'Синяя мечта'",
    price: 6100,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "Элитные",
    rating: 5,
    description:
      "Изысканный овальный венок с белыми розами по краю и синими розами в центре в белом обрамлении с золотой каймой",
  },
  {
    id: 43,
    name: "Венок-цветок 'Белая нежность'",
    price: 4200,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "Традиционные",
    rating: 5,
    description: "Необычный венок в форме цветка с белыми гвоздиками в центре и зеленым декоративным обрамлением",
  },
  {
    id: 44,
    name: "Венок-подкова 'Красная страсть'",
    price: 4800,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.0.3",
    category: "Классические",
    rating: 5,
    description: "Элегантный венок в форме подковы с красными лилиями и белыми розами в зеленом обрамлении",
  },
]

// Featured wreaths for home page
const featuredWreaths = [
  wreaths[23], // Овальный венок 'Роскошь'
  wreaths[24], // Овальный венок 'Золотой'
  wreaths[21], // Овальный венок 'Торжественный'
  wreaths[20], // Овальный венок 'Солнечный'
  wreaths[25], // Овальный венок 'Весенний'
  wreaths[26], // Овальный венок 'Контраст'
]
